# -*- coding: utf-8 -*-
"""lastexam.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eVSn0OFa61RMd8PFQjLZ3Qv8eWNM2LKh
"""

mystr="hello ai world"
print(mystr[6:8])

i=1
while True :
  print(i)
  i += 2
  if (i==5):
    break

series=range(5)
new_series=[num**2 for num in series]
print(new_series)